<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdvertisingTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    public function run()
    {
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 1,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 1,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 1,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 1,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 1,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 2,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 2,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 2,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 2,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,
            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 2,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
        DB::table('advertising')->insert([
            'advertiser_id' => 1,
            'category_id' => 1,
            'sub_category_id' => 4,
            'city_id' => 1,
            'package_id' => null,
            'lat' => null,
            'lng' => null,
            'title' => 'اختبار',
            'photos' => '["images/advertising-images/1597810306.jpg","images/advertising-images/1597810306.jpg"]',
            'price' => 200,
            'special_conditions' => 'special_conditions',
            'vedio_url' => null,
            'is_phone' => 0,
            'counter' => 0,

            'is_specialconditions' => 1,
            'insurance_price' => '100',
            'phone' => '0597988529',
            'address' => 'الرياض',
            'description' => 'description description',
            'comments' => 0,
            'status' => 2,
            'start_date' => '2020-08-21',
            'end_date' => '2021-09-29',
        ]);
    }
}

